[package]
name = "chatty"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
crossterm = {version="0.28.1", features=["event-stream"]}
itertools = "0.13.0"
ratatui = "0.27.0"
tokio = {version="1.39.2", features =["full"]}
tokio-stream = "0.1.15"

